baseURL = "https://sailes.co.uk"
languageCode = "en-us"
theme = "adritian-free-hugo-theme"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "css/main.css"
  [[params.plugins.css]]
  URL = "css/rad-icons.css"
  [[params.plugins.css]]
  URL = "css/custom.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "js/rad-animations.js"
  [[params.plugins.js]]
  URL = "js/sticky-header.js"
  [[params.plugins.js]]
  URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

  [[menu.header]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.header]]
  name = "Case Studies"
  URL = "#portfolio"
  weight = 3

  [[menu.header]]
  name = "Blog"
  URL = "/blog"
  weight = 4

  [[menu.header]]
  name = "Video"
  URL = "#video"
  weight = 5

  [[menu.footer]]
  name = "About"
  URL = "#about"
  weight = 2

  [[menu.footer]]
  name = "Portfolio"
  URL = "#portfolio"
  weight = 3

  [[menu.footer]]
  name = "Contact"
  URL = "#contact"
  weight = 4


[params]

  description = 'In depth Serverless content'
  images = ['images/default-open-graph.jpg']
  title = 'Mark Sailes'

  sections = ["showcase", "about", "education", "experience", "client-and-work", "video", "testimonial", "contact", "newsletter"]

  homepageExperienceCount = 6

  [params.google_analytics]
      code = "UA-XXXXX-Y"
      enabled = false
  
  [params.logo]
    text1 = "Mark"
    text2 = "Sailes"

  [params.footer]
      copyright = "© Mark Sailes. Free Hugo theme by Adrián Moreno Peña."
      [params.footer.radity_logo]
        x = "img/general/design-and-code-radity.png"
        _2x = "img/general/design-and-code-radity@2x.png"
        alt = "Design & Code - Radity"
